const express = require("express");
const FormsRouter = require("./routes/FormsRoute");
const TieupsRouter = require("./routes/TieupRoute");
const BikeConsult = require("./routes/bikeConsult");
const BikeService = require("./routes/bikeService");
const CarService = require("./routes/carService");
const CarConsult = require("./routes/carConsult");
const ECU = require("./routes/ecuTuning");
const Racing = require("./routes/racing");
const connectToDatabase = require("./database");
const bodyParser = require("body-parser");
const cookieParser = require("cookie-parser");
const cors = require("cors");
const app = express();
const PORT = process.env.PORT || 4000;
connectToDatabase();
app.use(cookieParser());
app.use(express.urlencoded({ extended: false }));
app.use(express.json({ limit: "20mb" }));
app.use(bodyParser.json({ limit: "20mb" }));
app.use(cors({ origin: ["http://localhost:3000"], credentials: true }));
app.use("/uploads", express.static("uploads"));
app.use("/car", CarConsult);
app.use("/bike", BikeConsult);
app.use("/carService", CarService);
app.use("/bikeService", BikeService);
app.use("/ecu", ECU);
app.use("/race", Racing);
app.use("/forms", FormsRouter);
app.use("/tieups", TieupsRouter);
app.listen(PORT, () => {
  console.log(`server started on port :${PORT}`);
});
